name: summify
description: "Summify Extension"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.6.0+17

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  path_provider: ^2.1.5
  dio: ^5.7.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  flutter_svg: ^2.0.17
  modal_bottom_sheet: ^3.0.0
  intl: ^0.20.2
  flutter_link_previewer: ^3.2.2
  flutter_gen_runner: ^5.10.0
  cached_network_image: ^3.4.1
  share_plus: ^10.1.4
  file_selector: ^1.0.3
  flutter_animate: ^4.5.2
  styled_text: ^8.1.0
  url_launcher: ^6.3.1
  file_picker: ^10.1.2
  flutter_local_notifications: ^19.1.0
#  receive_sharing_intent: ^1.8.1
  simple_animations: ^5.1.0
  stream_transform: ^2.1.1
  bloc_concurrency: ^0.3.0
  mixpanel_flutter: ^2.4.0
  in_app_review: ^2.0.10
  flutter_email_sender: ^7.0.0
#  status_bar_control: ^3.2.1
  purchases_flutter: ^8.7.2
  flutter_dialogs: ^3.0.0
  toastification: ^3.0.2
  auto_size_text: ^3.0.0
  hydrated_bloc: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo-1024.png"
  image_path_android: "assets/logo/logo-1024.png"
  min_sdk_android: 34

flutter:
  uses-material-design: true
  #  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/library/
    - assets/onboarding/
    - assets/set_up/
    - assets/flags/